package com.atguigu.crud.dao;

import com.atguigu.crud.bean.category;
import com.atguigu.crud.bean.categoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface categoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    long countByExample(categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int deleteByExample(categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int insert(category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int insertSelective(category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    List<category> selectByExample(categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") category record, @Param("example") categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int updateByExample(@Param("record") category record, @Param("example") categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int updateByPrimaryKeySelective(category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Thu Nov 28 15:56:29 CST 2019
     */
    int updateByPrimaryKey(category record);
}